name: Firebase App Distribution

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 6: Debug APK Path
      - name: Debug APK Path
        run: ls -al build/app/outputs/flutter-apk/

      # Step 7: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Step 8: Install Firebase CLI
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # Step 9: Authenticate with Firebase using Service Account
      - name: Authenticate with Firebase using Service Account
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./assets/keys/silicash.json
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud --quiet config set project silicash-14d97

      # Step 10: Validate Testers Group
      - name: Validate Testers Group
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./assets/keys/silicash.json
        run: |
          firebase appdistribution:testers:list --app 1:611760302482:android:268298bac91aea7fdfb94b \
            --project silicash-14d97

      # Step 11: Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./assets/keys/silicash.json
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:611760302482:android:268298bac91aea7fdfb94b \
            --release-notes "Automated release from GitHub Actions" \
            --groups "testers" \
            --project silicash-14d97
